import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";

const OutfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Bookify | Online Book Borrowing Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${OutfitFont.variable} h-full antialiased`}>
      <body className="min-h-screen">
        <Navbar />
        <Toaster position="top-center" />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
